### PR TITLE
Pretty print + fix comments

### LINKED ISSUE #155: Do something with newlines in SDLWriter
Unify newlines or add setting.

### PR DESCRIPTION
**Pull request by sungam3r**
Fixes #155 and partially #173 . SDLWriter began to work **much** better, I checked it on a variety of new tests. Nevertheless, I am absolutely sure that I still need to make changes and check all the situations (comments/descriptions on all node types, indentation, formatting).

### CODE REVIEW

File: src/GraphQLParser/NotNullWhenAttribute.cs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+#if NETSTANDARD2_0
+
+// https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs#L69
+namespace System.Diagnostics.CodeAnalysis;
+
+/// <summary>Specifies that when a method returns <see cref="ReturnValue"/>, the parameter will not be null even if the corresponding type allows it.</summary>
+[AttributeUsage(AttributeTargets.Parameter, Inherited = false)]
+internal sealed class NotNullWhenAttribute : Attribute
```
Comment (sungam3r) [inline src/GraphQLParser/NotNullWhenAttribute.cs:8]: Needed for `TryPeek`.

File: src/GraphQLParser/ParserContext.Parse.cs [hunk 2]
```diff
@@ -524,31 +524,31 @@ private GraphQLField ParseField()
         // start of alias (if exists) equals start of field
         int start = _currentToken.Start;
 
-        var nameOrAliasComment = GetComment();
+        var comment = GetComment(); // Greedy parsing for comment here - we read comment for field itself, not for alias.
```
Comment (sungam3r) [inline src/GraphQLParser/ParserContext.Parse.cs:527]: @Shane32 I changed commmentss parsing for `Field`. Now it corresponds to the rest of the code when the comment refers to the object that is parsing by this method. I also changed tests.

File: src/GraphQLParser/Visitors/SDLWriter.cs [hunk 3]
```diff
@@ -976,3 +1056,25 @@ private static async ValueTask WriteEncodedString(TContext context, ROM value)
...
+
+/// <summary>
+/// Options for <see cref="SDLWriter{TContext}"/>.
+/// </summary>
+public class SDLWriterOptions
+{
+    /// <summary>
+    /// Write comments into the output.
+    /// </summary>
+    public bool WriteComments { get; set; }
```
Comment (Shane32) [inline src/GraphQLParser/Visitors/SDLWriter.cs:1068]: Does 'false' match default behavior before this option existed?  If not, this would be a breaking change.

Comment (Shane32) [reply src/GraphQLParser/Visitors/SDLWriter.cs:1068]: Note: I'm happy with `false` as default for v5, but if it used to print comments before, it should be `true` v4 and have a note in the migration doc for v5.  I see this targets `master`.

Comment (Shane32) [reply src/GraphQLParser/Visitors/SDLWriter.cs:1068]: Wrong repo; was thinking of the ASTPrinter in graphql.net .  nevermind!

**Review by Shane32 — APPROVED** [review]

File: src/GraphQLParser/Visitors/SDLWriter.cs (hunk 3 above)
Comment (sungam3r) [reply src/GraphQLParser/Visitors/SDLWriter.cs:1068]: Oops , I forgot about setting `true`. When I wrote tests I used default value :
изображение

Comment (sungam3r) [reply src/GraphQLParser/Visitors/SDLWriter.cs:1068]: > but if it used to print comments before

There was no "before". All this code has never been released. Let's keep `false` for default.
